# Generated by Django 4.2.3 on 2023-10-03 06:04

import app.models
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='In which category you want to seperate your project layer', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Description about this category', verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalStandardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', app.models.CaseInsensitiveCharField(help_text='Standard Category name', max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Description about this category', verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='In which Sub category you want to seperate your project layer', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Description about this category', verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('standard_category', models.ForeignKey(help_text='Standard Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.globalstandardcategory', verbose_name='Standard Category')),
            ],
            options={
                'unique_together': {('standard_category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GlobalCategoryStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill', colorfield.fields.ColorField(default='#2c3e50', help_text='Fill color for the polygon', image_field=None, max_length=25, samples=None, verbose_name='Fill Color')),
                ('fill_opacity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('stroke', colorfield.fields.ColorField(default='#ffffff', help_text='Stroke color for the polygon', image_field=None, max_length=25, samples=None, verbose_name='Stroke Color')),
                ('stroke_width', models.PositiveIntegerField(default=1)),
                ('xml', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('category', models.OneToOneField(help_text='Style related to this Category', on_delete=django.db.models.deletion.PROTECT, to='app.globalcategory', verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='globalcategory',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Sub Category related to the project', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.globalsubcategory', verbose_name='Sub Category'),
        ),
    ]
