# Generated by Django 4.2.3 on 2023-10-03 06:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_globalcategory_globalstandardcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcategorystyle',
            name='stroke',
            field=colorfield.fields.ColorField(default='#C86AFF', help_text='Stroke color for the polygon', image_field=None, max_length=25, samples=None, verbose_name='Stroke Color'),
        ),
    ]
