# Generated by Django 4.2.3 on 2023-10-03 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_globalcategorystyle_stroke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcategory',
            name='sub_category',
            field=models.ForeignKey(help_text='Sub Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.globalsubcategory', verbose_name='Sub Category'),
        ),
    ]
