# Generated by Django 4.2.3 on 2023-10-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_standardcategory_subcategory_categorystyle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='global_standard_category',
            field=models.ForeignKey(default=1, help_text='Global Standard Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.globalstandardcategory', verbose_name='Global Standard Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='global_sub_category',
            field=models.ForeignKey(default=1, help_text='Global Sub Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.globalsubcategory', verbose_name='Global Sub Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorystyle',
            name='global_category',
            field=models.OneToOneField(default=1, help_text='Geometry related to this Category', on_delete=django.db.models.deletion.PROTECT, to='app.globalcategory', verbose_name='Global Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='global_standard_category',
            field=models.ForeignKey(default=1, help_text='Global Standard Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.globalstandardcategory', verbose_name='Global Standard Category'),
            preserve_default=False,
        ),
    ]
