# Generated by Django 4.2.3 on 2023-10-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category_global_standard_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcategory',
            name='standard_category',
            field=models.ForeignKey(default=1, help_text='Standard Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.globalstandardcategory', verbose_name='Standard Category'),
            preserve_default=False,
        ),
    ]
