# Generated by Django 4.2.3 on 2023-10-04 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_globalcategory_standard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardcategory',
            name='global_standard_category',
            field=models.ForeignKey(default=1, help_text='Global Standard Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.globalstandardcategory', verbose_name='Global Standard Category'),
            preserve_default=False,
        ),
    ]
