# Generated by Django 4.2.3 on 2023-10-04 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_standardcategory_global_standard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='global_category',
            field=models.ForeignKey(default=1, help_text='Global Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.globalcategory', verbose_name='Global  Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='global_sub_category',
            field=models.ForeignKey(default=1, help_text='Global Sub Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.globalsubcategory', verbose_name='Global Sub Category'),
            preserve_default=False,
        ),
    ]
