# Generated by Django 4.2.3 on 2023-10-04 09:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_linestringdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('attributes', models.JSONField(blank=True, default=dict, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Cateogyr related to this Point', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='Category')),
                ('project', models.ForeignKey(help_text='Point related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.project', verbose_name='Project')),
                ('standard_category', models.ForeignKey(blank=True, help_text='Standard Category related to the Point', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.standardcategory', verbose_name='Standard Category')),
                ('sub_category', models.ForeignKey(blank=True, help_text='Sub Category related to the Point', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.subcategory', verbose_name='Sub Category')),
            ],
            options={
                'verbose_name_plural': 'PointData',
            },
        ),
    ]
