# Generated by Django 4.2.3 on 2023-10-06 04:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_linestringdata_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for the rater data', max_length=255, verbose_name='Name')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('shape_file', models.FileField(upload_to='Uploads/RasterData')),
                ('project', models.ForeignKey(help_text='Point related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.project', verbose_name='Project')),
            ],
            options={
                'verbose_name_plural': 'RasterData',
            },
        ),
    ]
