# Generated by Django 4.2.3 on 2023-10-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rasterdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rasterdata',
            old_name='shape_file',
            new_name='tif_file',
        ),
    ]
