# Generated by Django 4.2.3 on 2023-10-09 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_shape_file_rasterdata_tif_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterdata',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
