# Generated by Django 4.2.3 on 2023-10-10 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_rasterdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystyle',
            name='category',
            field=models.OneToOneField(help_text='Geometry related to this Category', on_delete=django.db.models.deletion.DO_NOTHING, to='app.category', verbose_name='Category'),
        ),
    ]
