# Generated by Django 4.2.3 on 2023-10-10 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_categorystyle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linestringdata',
            name='category',
            field=models.ForeignKey(help_text='Cateogyr related to this LineString', on_delete=django.db.models.deletion.DO_NOTHING, to='app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='category',
            field=models.ForeignKey(help_text='Cateogyr related to this Point', on_delete=django.db.models.deletion.DO_NOTHING, to='app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='polygondata',
            name='category',
            field=models.ForeignKey(help_text='Cateogyr related to this polygon', on_delete=django.db.models.deletion.DO_NOTHING, to='app.category', verbose_name='Category'),
        ),
    ]
