# Generated by Django 4.2.3 on 2023-10-10 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_linestringdata_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystyle',
            name='global_category',
            field=models.OneToOneField(help_text='Geometry related to this Category', on_delete=django.db.models.deletion.DO_NOTHING, to='app.globalcategory', verbose_name='Global Category'),
        ),
        migrations.AlterField(
            model_name='categorystyle',
            name='project',
            field=models.ForeignKey(help_text='Style related to the project', on_delete=django.db.models.deletion.DO_NOTHING, to='app.project', verbose_name='Project'),
        ),
    ]
