# Generated by Django 4.2.3 on 2023-10-10 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_categorystyle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystyle',
            name='global_category',
            field=models.OneToOneField(blank=True, help_text='Geometry related to this Category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.globalcategory', verbose_name='Global Category'),
        ),
        migrations.AlterField(
            model_name='categorystyle',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Style related to the project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='linestringdata',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Cateogyr related to this LineString', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='linestringdata',
            name='project',
            field=models.ForeignKey(blank=True, help_text='LineString related to the project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='linestringdata',
            name='standard_category',
            field=models.ForeignKey(blank=True, help_text='Standard Category related to the LineString', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.standardcategory', verbose_name='Standard Category'),
        ),
        migrations.AlterField(
            model_name='linestringdata',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Sub Category related to the LineString', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subcategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Cateogyr related to this Point', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Point related to the project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='standard_category',
            field=models.ForeignKey(blank=True, help_text='Standard Category related to the Point', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.standardcategory', verbose_name='Standard Category'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Sub Category related to the Point', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subcategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='polygondata',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Cateogyr related to this polygon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='polygondata',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Polygon related to the project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='polygondata',
            name='standard_category',
            field=models.ForeignKey(blank=True, help_text='Standard Category related to the polygon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.standardcategory', verbose_name='Standard Category'),
        ),
        migrations.AlterField(
            model_name='polygondata',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Sub Category related to the polygon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subcategory', verbose_name='Sub Category'),
        ),
    ]
