# Generated by Django 4.2.3 on 2023-10-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_rasterdata_uuid_rasterdata_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterdata',
            name='status',
            field=models.CharField(default='Uploaded', help_text='Status for the task', max_length=255, verbose_name='Status'),
        ),
    ]
