# Generated by Django 4.2.3 on 2023-11-02 03:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_rasterdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterdata',
            name='file_name',
            field=models.CharField(default='', help_text='Name for the rater file', max_length=255, verbose_name='File Name'),
        ),
        migrations.AddField(
            model_name='rasterdata',
            name='projection',
            field=models.CharField(default='Not Defined', help_text='Projection of the Tif', max_length=255, verbose_name='Projection'),
        ),
        migrations.AddField(
            model_name='rasterdata',
            name='screenshot_image',
            field=models.ImageField(default='Uploads/RasterImage/raster_sample.png', upload_to='Uploads/RasterImage', validators=[app.models.validate_png]),
        ),
    ]
