# Generated by Django 4.2.3 on 2023-11-08 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0028_rasterdata_file_name_rasterdata_projection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='basic', help_text='Name of the Role', max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(help_text='Role of the user', on_delete=django.db.models.deletion.DO_NOTHING, to='app.role', verbose_name='Role')),
                ('user', models.ForeignKey(help_text='The person who created the project', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
