# Generated by Django 4.2.3 on 2023-11-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_linestringdata_is_deleted_linestringdata_is_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deleting',
        ),
        migrations.AlterField(
            model_name='project',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
    ]
