# Generated by Django 4.2.3 on 2023-11-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_project_deleting_alter_project_is_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
    ]
