# Generated by Django 4.2.3 on 2023-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstandardcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalstandardcategory',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalstandardcategory',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
