# Generated by Django 4.2.3 on 2023-11-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_globalsubcategory_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalcategory',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalcategory',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
