# Generated by Django 4.2.3 on 2023-11-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_globalcategory_is_deleted_globalcategory_is_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcategorystyle',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalcategorystyle',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalcategorystyle',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
