# Generated by Django 4.2.3 on 2023-11-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_globalcategorystyle_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardcategory',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='standardcategory',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
    ]
