# Generated by Django 4.2.3 on 2023-11-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_standardcategory_is_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
