# Generated by Django 4.2.3 on 2023-11-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_subcategory_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorystyle',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='polygondata',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
