# Generated by Django 4.2.3 on 2023-11-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_category_is_edited_categorystyle_is_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linestringdata',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rasterdata',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
