# Generated by Django 4.2.3 on 2023-11-09 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_userrole_created_at_userrole_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproject',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
