# Generated by Django 4.2.3 on 2023-11-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_userproject_created_at_userproject_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterdata',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
    ]
