# Generated by Django 4.2.3 on 2023-11-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_rasterdata_is_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categorystyle',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='linestringdata',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='polygondata',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
    ]
