# Generated by Django 4.2.3 on 2023-11-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_category_is_display_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linestringdata',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pointdata',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='polygondata',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rasterdata',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
