# Generated by Django 4.2.3 on 2023-11-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_rename_created_linestringdata_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalcategorystyle',
            name='xml',
        ),
    ]
