# Generated by Django 4.2.3 on 2023-11-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_remove_globalcategorystyle_xml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorystyle',
            name='xml',
        ),
    ]
