# Generated by Django 4.2.3 on 2023-11-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_categorystyle_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcategory',
            name='type_of_geometry',
            field=models.CharField(default='Polygon', max_length=255),
        ),
    ]
