# Generated by Django 4.2.3 on 2023-11-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_globalcategory_type_of_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type_of_geometry',
            field=models.CharField(default='Polygon', max_length=255),
        ),
    ]
