# Generated by Django 4.2.3 on 2023-11-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_category_type_of_geometry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='project admin', help_text='Name of the Role', max_length=255, verbose_name='Name'),
        ),
    ]
