# Generated by Django 4.2.3 on 2023-11-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_project_options_alter_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='created_by',
        ),
    ]
