# Generated by Django 4.2.3 on 2023-11-11 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_category_created_by_categorystyle_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='client',
            field=models.ForeignKey(help_text='Client Associated with this', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='categorystyle',
            name='client',
            field=models.ForeignKey(help_text='Client Associated with this', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='linestringdata',
            name='client',
            field=models.ForeignKey(help_text='Client Associated with this', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='client',
            field=models.ForeignKey(help_text='Client Associated with this', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='polygondata',
            name='client',
            field=models.ForeignKey(help_text='Client Associated with this', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(help_text='Client Associated with this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='rasterdata',
            name='client',
            field=models.ForeignKey(help_text='Client Associated with this', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='client',
            field=models.ForeignKey(help_text='Client Associated with this', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client'),
        ),
    ]
