# Generated by Django 4.2.3 on 2023-11-11 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_standardcategory_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rasterdata',
            options={'verbose_name_plural': 'Property'},
        ),
        migrations.AddField(
            model_name='category',
            name='properti',
            field=models.ForeignKey(help_text='Category related to this property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rasterdata', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='categorystyle',
            name='properti',
            field=models.ForeignKey(help_text='Category Style related to this property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rasterdata', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='linestringdata',
            name='properti',
            field=models.ForeignKey(help_text='LineString related to this property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rasterdata', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='properti',
            field=models.ForeignKey(help_text='Point related to this property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rasterdata', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='polygondata',
            name='properti',
            field=models.ForeignKey(help_text='Polygon related to this property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rasterdata', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='standardcategory',
            name='properti',
            field=models.ForeignKey(help_text='Standard Category related to this property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rasterdata', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='properti',
            field=models.ForeignKey(help_text='Sub Category related to this property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rasterdata', verbose_name='Property'),
        ),
    ]
