# Generated by Django 4.2.3 on 2023-12-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_userrole_client_userrole_project_userrole_properti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linestringdata',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linestringdata',
            name='standard_category_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linestringdata',
            name='sub_category_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='standard_category_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='sub_category_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='polygondata',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='polygondata',
            name='standard_category_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='polygondata',
            name='sub_category_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='polygondata',
            name='project',
            field=models.ForeignKey(help_text='Polygon related to the project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='polygondata',
            name='properti',
            field=models.ForeignKey(help_text='Polygon related to this property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rasterdata', verbose_name='map'),
        ),
    ]
