# Generated by Django 4.2.3 on 2024-03-02 01:24

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0063_objdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', app.models.CaseInsensitiveCharField(help_text='Standard Inspection Name', max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(default='', help_text='Description', verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(help_text='The person who created', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
        migrations.CreateModel(
            name='SubInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sub Inspection Name', max_length=255, verbose_name='Name')),
                ('description', models.TextField(default='', help_text='Description', verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(help_text='The person who created', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('standard_inspection', models.ForeignKey(help_text='Standard Inspection related to this sub inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.standardinspection', verbose_name='Standard Inspection')),
            ],
            options={
                'unique_together': {('standard_inspection', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Inspection Name', max_length=255, verbose_name='Name')),
                ('description', models.TextField(default='', help_text='Description', verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(help_text='The person who created', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('standard_inspection', models.ForeignKey(help_text='Standard Inspection related to this inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.standardinspection', verbose_name='Standard Inspection')),
                ('sub_inspection', models.ForeignKey(help_text='Sub Inspection related to this inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subinspection', verbose_name='Sub Inspection')),
            ],
        ),
    ]
