# Generated by Django 4.2.3 on 2024-03-02 02:17

import colorfield.fields
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0064_standardinspection_subinspection_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Inspection Report Name', max_length=255, verbose_name='Name')),
                ('date_of_inspection', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of Inspection', verbose_name='Date of Inspection')),
                ('description', models.TextField(blank=True, default='', help_text='Description', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(help_text='The person who created', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Uploads/InspectionPhotos')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the point', null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the point', null=True, verbose_name='Longitude')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('description', models.TextField(blank=True, default='', help_text='Description', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(help_text='The person who created', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('inspection_report', models.ForeignKey(help_text='Inspection Report related to this photo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.inspectionreport', verbose_name='Inspection Report')),
            ],
        ),
        migrations.CreateModel(
            name='InpsectionPhotoGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', help_text='Description', null=True, verbose_name='Description')),
                ('caption', models.CharField(blank=True, help_text='Caption for the point', max_length=255, null=True, verbose_name='Caption')),
                ('x', models.FloatField(blank=True, help_text='X coordinate of the point', null=True, verbose_name='X')),
                ('y', models.FloatField(blank=True, help_text='Y coordinate of the point', null=True, verbose_name='Y')),
                ('height', models.FloatField(blank=True, help_text='Height of the point', null=True, verbose_name='Height')),
                ('width', models.FloatField(blank=True, help_text='Width of the point', null=True, verbose_name='Width')),
                ('fill_color', colorfield.fields.ColorField(default='#2c3e50', help_text='Fill color for the polygon', image_field=None, max_length=25, samples=None, verbose_name='Fill Color')),
                ('fill_opacity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('stroke_color', colorfield.fields.ColorField(default='#ffffff', help_text='Stroke color for the polygon', image_field=None, max_length=25, samples=None, verbose_name='Stroke Color')),
                ('stroke_opacity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('rotation', models.FloatField(blank=True, help_text='Rotation of the point', null=True, verbose_name='Rotation')),
                ('severity', models.CharField(blank=True, help_text='Severity of the point', max_length=255, null=True, verbose_name='Severity')),
                ('cost', models.FloatField(blank=True, help_text='Cost of the point', null=True, verbose_name='Cost')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(help_text='The person who created', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('inspection', models.ForeignKey(help_text='Inspection related to this geometry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.inspection', verbose_name='Inspection')),
                ('inspection_photo', models.ForeignKey(help_text='Inspection Photo related to this detail', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.inspectionphoto', verbose_name='Inspection Photo')),
                ('standard_inspection', models.ForeignKey(help_text='Standard Inspection related to this geometry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.standardinspection', verbose_name='Standard Inspection')),
                ('sub_inspection', models.ForeignKey(help_text='Sub Inspection related to this geometry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subinspection', verbose_name='Sub Inspection')),
            ],
        ),
    ]
