# Generated by Django 4.2.3 on 2024-03-02 06:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_remove_inspection_project_inspectionreport_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='fill_color',
            field=colorfield.fields.ColorField(default='#2c3e50', help_text='Fill color for the polygon', image_field=None, max_length=25, samples=None, verbose_name='Fill Color'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='fill_opacity',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='inspection',
            name='stroke_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Stroke coloe for the polygon', image_field=None, max_length=25, samples=None, verbose_name='Stroke Color'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='stroke_width',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
