# Generated by Django 4.2.3 on 2024-03-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_remove_inpsectionphotogeometry_stroke_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='client',
            field=models.ForeignKey(help_text='Client related to this inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client'),
        ),
    ]
