# Generated by Django 4.2.3 on 2024-03-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_inspectionreport_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='date_of_inspection',
            field=models.CharField(help_text='Date of Inspection', max_length=500, verbose_name='Date of Inspection'),
        ),
    ]
