# Generated by Django 4.2.3 on 2024-03-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_inspectionreport_date_of_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionphoto',
            name='is_inspected',
            field=models.BooleanField(default=False),
        ),
    ]
