# Generated by Django 4.2.3 on 2024-03-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_alter_inspection_standard_inspection_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subinspection',
            unique_together=set(),
        ),
    ]
