# Generated by Django 4.2.3 on 2024-03-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_alter_subinspection_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpsectionphotogeometry',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the geometry', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
