# Generated by Django 4.2.3 on 2024-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_inpsectionphotogeometry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpsectionphotogeometry',
            name='created',
            field=models.BooleanField(default=True),
        ),
    ]
