# Generated by Django 4.2.3 on 2024-03-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_projectpolygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpolygon',
            name='client',
            field=models.ForeignKey(help_text='Client Associated with this polygon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client'),
        ),
    ]
