# Generated by Django 4.2.3 on 2024-03-28 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_projectpolygon_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystyle',
            name='global_category',
            field=models.ForeignKey(help_text='Geometry related to this Category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.globalcategory', verbose_name='Global Category'),
        ),
    ]
