# Generated by Django 4.2.3 on 2024-04-10 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0080_alter_categorystyle_global_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringFileUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(null=True)),
                ('name', models.CharField(help_text='Name for the rater data', max_length=255, verbose_name='Name')),
                ('file_name', models.CharField(default='', help_text='Name for the rater file', max_length=255, verbose_name='File Name')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Uploaded', help_text='Status for the task', max_length=255, verbose_name='Status')),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('projection', models.CharField(default='Not Defined', help_text='Projection of the ', max_length=255, verbose_name='Projection')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_display', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('client', models.ForeignKey(help_text='Client Associated with this', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(help_text='The person who created', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(help_text='Point related to the project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project', verbose_name='Project')),
            ],
            options={
                'verbose_name_plural': 'MeasuringFileUpload',
            },
        ),
    ]
