# Generated by Django 4.2.3 on 2024-04-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_measuringfileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuringfileupload',
            name='total_features',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
