# Generated by Django 4.2.3 on 2024-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_measuringfileupload_total_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='linestringdata',
            name='task_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='task_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='polygondata',
            name='task_id',
            field=models.UUIDField(null=True),
        ),
    ]
