# Generated by Django 4.2.3 on 2024-04-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_alter_role_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='project',
            field=models.ManyToManyField(blank=True, help_text='Project associated with this role', null=True, to='app.project', verbose_name='Project'),
        ),
    ]
