# Generated by Django 4.2.3 on 2024-04-26 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0086_alter_role_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client associated with this role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The person who created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
