# Generated by Django 4.2.3 on 2024-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_alter_role_client_alter_role_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.TextField(default='', help_text='More in-depth description of the project', verbose_name='Description'),
        ),
    ]
