# Generated by Django 4.2.3 on 2024-04-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_alter_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.TextField(blank=True, default='', help_text='3d url of the project', null=True, verbose_name='URL'),
        ),
    ]
