# Generated by Django 4.2.3 on 2024-04-30 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0090_alter_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Indoor Name', max_length=255, verbose_name='Name')),
                ('url', models.TextField(blank=True, default='', help_text='Url for indoor', null=True, verbose_name='Url')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(help_text='Client related to this indoor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(help_text='The person who created', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(help_text='Project related to this indoor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project', verbose_name='Project')),
            ],
        ),
    ]
