# Generated by Django 4.2.3 on 2024-05-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_globalcategory_extra_fileds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalcategory',
            name='extra_fileds',
        ),
    ]
