# Generated by Django 4.2.3 on 2024-05-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_globalcategory_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcategory',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
