# Generated by Django 4.2.3 on 2024-06-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_alter_globalcategory_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterdata',
            name='file_path',
            field=models.CharField(default='', help_text='Path for the raster file', max_length=255, verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='rasterdata',
            name='tif_file',
            field=models.FileField(blank=True, null=True, upload_to='Uploads/RasterData'),
        ),
    ]
