# Generated by Django 4.2.3 on 2024-06-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_rasterdata_file_path_alter_rasterdata_tif_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='linestringdata',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='linestringdata',
            name='global_category',
            field=models.ForeignKey(blank=True, help_text='Global Category related to the polygon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.globalcategory', verbose_name='Global Category'),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='global_category',
            field=models.ForeignKey(blank=True, help_text='Global Category related to the polygon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.globalcategory', verbose_name='Global Category'),
        ),
        migrations.AddField(
            model_name='polygondata',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='polygondata',
            name='global_category',
            field=models.ForeignKey(blank=True, help_text='Global Category related to the polygon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.globalcategory', verbose_name='Global Category'),
        ),
    ]
