# Generated by Django 4.2.3 on 2024-06-25 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0097_linestringdata_extra_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='administrator',
            field=models.CharField(blank=True, help_text='Administrator name', max_length=255, null=True, verbose_name='Administrator name'),
        ),
        migrations.AddField(
            model_name='client',
            name='cvr_number',
            field=models.CharField(blank=True, help_text='CVR Number', max_length=255, null=True, verbose_name='CVR Number'),
        ),
        migrations.AddField(
            model_name='client',
            name='lbf_number',
            field=models.CharField(blank=True, help_text='LBF Number', max_length=255, null=True, verbose_name='LBF Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Client associated user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_user', to=settings.AUTH_USER_MODEL, verbose_name='Client User'),
        ),
    ]
