# Generated by Django 4.2.3 on 2024-07-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_client_administrator_client_cvr_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalcategory',
            name='extra_fields',
        ),
        migrations.RemoveField(
            model_name='linestringdata',
            name='extra_fields',
        ),
        migrations.RemoveField(
            model_name='pointdata',
            name='extra_fields',
        ),
        migrations.RemoveField(
            model_name='polygondata',
            name='extra_fields',
        ),
    ]
