# Generated by Django 4.2.3 on 2024-07-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_remove_globalcategory_extra_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcategory',
            name='extra_fields',
            field=models.TextField(default='[]', help_text='Extra fields for this category', verbose_name='Extra Fields'),
        ),
        migrations.AddField(
            model_name='linestringdata',
            name='extra_fields',
            field=models.TextField(default='[]', help_text='Extra fields for this category', verbose_name='Extra Fields'),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='extra_fields',
            field=models.TextField(default='[]', help_text='Extra fields for this category', verbose_name='Extra Fields'),
        ),
        migrations.AddField(
            model_name='polygondata',
            name='extra_fields',
            field=models.TextField(default='[]', help_text='Extra fields for this category', verbose_name='Extra Fields'),
        ),
    ]
